bucket.name: ${BUCKET_NAME}

quarkus :
  s3.aws:
    region: ${AWS_REGION}
    credentials.type: "default"

"%dev":
  bucket:
    name: "test-bucket"

  quarkus:
    s3:
      devservices:
        buckets: "test-bucket"
      aws:
        region: "us-east-1"
        credentials:
          type: "static"
          static-provider:
            access-key-id: "test-key"
            secret-access-key: "test-secret"

validation-messages:
  system:
    error: "An unexpected error has occurred."

image:
  accepted-mime-types: "image/jpeg, image/png, image/gif"

  size:
    square:
      aspect-ratio: "1:1"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    panoramic:
      aspect-ratio: "2:1"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    rectangular:
      aspect-ratio: "4:3"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    landscape:
      aspect-ratio: "16:9"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

"%test":
  image:
    size:
      square:
        aspect-ratio: "1:1"
        min-width: "400"
        thumbnail:
          scaling-factor: "0.1"

      panoramic:
        aspect-ratio: "2:1"
        min-width: "400"
        medium:
          scaling-factor: "0.7"