test-variables:
  bucket-name: "test-bucket"
  queue-name: "test-queue"
  aws-region: "us-east-1"
  aws-access-key-id: "test-key"
  aws-secret-access-key: "test-secret"

bucket.name: ${BUCKET_NAME}

queue:
  image-processing-queue:
    url: ${IMAGE_PROCESSING_QUEUE_URL}

quarkus :
  oidc:
    auth-server-url: ${AUTH_SERVER_URL}
    client-id: ${OIDC_CLIENT_ID}
    credentials:
      secret: ${OIDC_CLIENT_SECRET}

  s3.aws:
    region: ${AWS_REGION}
    credentials.type: "default"

  mongodb:
    database: ${MONGODB_DATABASE_NAME}

validation-messages:
  system:
    error: "An unexpected error has occurred."

image-processing-properties:
  timeout: ${IMAGE_PROCESSING_TIMEOUT:PT10M}

image:
  accepted-mime-types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"

  size:
    square:
      aspect-ratio: "1:1"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    panoramic:
      aspect-ratio: "2:1"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    rectangular:
      aspect-ratio: "4:3"
      min-width: "800"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    landscape:
      aspect-ratio: "16:9"
      min-width: "400"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.4"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

"%prod":
  quarkus:
    mongodb:
      connection-string: ${MONGODB_CONNECTION_STRING}

"%dev":
  queue:
    image-processing-queue:
      url: ${test-variables.queue-name}

  bucket:
    name: ${test-variables.bucket-name}

  quarkus:
    sqs:
      devservices:
        queues: ${test-variables.queue-name}
      aws:
        region: ${test-variables.aws-region}
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}

    s3:
      devservices:
        buckets: ${test-variables.bucket-name}
      aws:
        region: ${test-variables.aws-region}
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}

"%test":

  queue:
    image-processing-queue:
      url: ${test-variables.queue-name}

  bucket:
    name: ${test-variables.bucket-name}

  quarkus:
    sqs:
      devservices:
        queues: ${test-variables.queue-name}
      aws:
        region: ${test-variables.aws-region}
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}

    s3:
      devservices:
        buckets: ${test-variables.bucket-name}
      aws:
        region: ${test-variables.aws-region}
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}

  image:
    size:
      square:
        aspect-ratio: "1:1"
        min-width: "400"
        thumbnail:
          scaling-factor: "0.1"

      panoramic:
        aspect-ratio: "2:1"
        min-width: "400"
        medium:
          scaling-factor: "0.7"