image-processing-properties:
  timeout: ${IMAGE_PROCESSING_TIMEOUT:PT10M}

image:
  accepted-mime-types:
    - "image/jpeg"
    - "image/png"
    - "image/gif"

  size:
    square:
      aspect-ratio: "1:1"
      min-width: "1200"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.3"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    panoramic:
      aspect-ratio: "2:1"
      min-width: "2000"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.3"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    rectangular:
      aspect-ratio: "4:3"
      min-width: "1200"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.3"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"

    wide:
      aspect-ratio: "16:9"
      min-width: "1600"
      thumbnail:
        scaling-factor: "0.1"
      small:
        scaling-factor: "0.3"
      medium:
        scaling-factor: "0.7"
      large:
        scaling-factor: "1"