test-variables:
  bucket-name: "test-bucket"
  processing-queue-name: "processing-test-queue"
  aws-region: "us-east-1"
  aws-access-key-id: "test-key"
  aws-secret-access-key: "test-secret"

bucket.name: ${BUCKET_NAME}
lambda:
  classifier:
    function-name: ${IMAGE_CLASSIFIER_LAMBDA_NAME:image-classifier}

quarkus:
  native:
    additional-build-args: --initialize-at-run-time=net.coobird.thumbnailator.resizers.AbstractResizer\,net.coobird.thumbnailator.resizers.BilinearResizer\,net.coobird.thumbnailator.resizers.configurations.AlphaInterpolation\,net.coobird.thumbnailator.resizers.configurations.Antialiasing\,net.coobird.thumbnailator.resizers.configurations.Dithering\,net.coobird.thumbnailator.resizers.configurations.Rendering\,net.coobird.thumbnailator.resizers.NullResizer\,net.coobird.thumbnailator.resizers.ProgressiveBilinearResizer\,net.coobird.thumbnailator.resizers.Resizers

  oidc:
    auth-server-url: ${AUTH_SERVER_URL}
    client-id: ${OIDC_CLIENT_ID}
    credentials:
      secret: ${OIDC_CLIENT_SECRET}
    roles:
      role-claim-path: "permissions"

  mongodb:
    database: ${MONGODB_DATABASE_NAME}

  log:
    console:
      format: "%d{yyyy.MM.dd HH:mm:ss:SSSZ} %-5p [%c{2.}] (%t) message id= %X{message.id}, requester= %X{requester}, message= %m %n"

validation-messages:
  system:
    error: "An unexpected error has occurred."

image-processing-properties:
  timeout: ${IMAGE_PROCESSING_TIMEOUT:PT10M}

"%prod":
  quarkus:
    mongodb:
      connection-string: ${MONGODB_CONNECTION_STRING}

"%dev":

  bucket:
    name: ${test-variables.bucket-name}

  quarkus:
    lambda:
      mock-event-server:
        dev-port: "8082"
    mongodb:
      connection-string: "mongodb://localhost:8180"
    sqs:
      devservices:
        queues: ${test-variables.processing-queue-name}
        shared: true
      aws:
        credentials:
          type: static
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}
    s3:
      path-style-access: true
      devservices:
        buckets: ${test-variables.bucket-name}
        shared: true
      aws:
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}

"%test":

  bucket:
    name: ${test-variables.bucket-name}

  quarkus:
    mongodb:
      database: "test-db"
      devservices:
        port: "56000"
    lambda:
      mock-event-server:
        test-port: "8083"
    sqs:
      aws:
        credentials:
          type: static
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}
      devservices:
        queues: ${test-variables.processing-queue-name}
        enabled: true
        shared: true
    s3:
      region: ${test-variables.aws-region}
      devservices:
        buckets: ${test-variables.bucket-name}
      aws:
        credentials:
          type: "static"
          static-provider:
            access-key-id: ${test-variables.aws-access-key-id}
            secret-access-key: ${test-variables.aws-secret-access-key}
    aws:
      devservices:
        localstack:
          port: "56100"

  image:
    size:
      square:
        aspect-ratio: "1:1"
        min-width: "400"
        thumbnail:
          scaling-factor: "0.1"

      panoramic:
        aspect-ratio: "2:1"
        min-width: "400"
        medium:
          scaling-factor: "0.7"
