name: Build and push image classifier image

on:
  workflow_call:
    inputs:
      IMAGES_BUCKET_NAME:
        required: true
        type: string
      AWS_REGION:
        required: true
        type: string
      tag-as-latest:
        required: true
        type: boolean
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_ACCESS_SECRET_KEY:
        required: true
    outputs:
      image_tag:
        description: "The generated image tag"
        value: ${{jobs.build-docker-image.outputs.image_tag}}
      full_image_path:
        description: "The full path of the uploaded image with tag"
        value: ${{jobs.build-docker-image.outputs.image_path}}

env:
  NLTK_DATA: ./nltk_data
  IMAGES_BUCKET_NAME: ${{inputs.IMAGES_BUCKET_NAME}}
  SYSTEM_MODEL_PATH: image-classifier/local_pretrained_model
  ECR_REPOSITORY: image-picker/image-classifier

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{steps.upload-image.outputs.image_tag}}
      image_path: ${{steps.upload-image.outputs.image_path}}
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Checkout project sources
        uses: actions/checkout@v3
        with:
          lfs: true
      - name: Install NLTK
        run: pip install nltk

      - name: Download WordNet
        run: |
          mkdir -p $NLTK_DATA
          python -c "import nltk; nltk.download('wordnet')"

      - name: build docker container
        id: build-docker-container
        env:
          IMAGE_TAG: ${{github.run_number}}-${{steps.date.outputs.date}}
        run: |
          docker build --provenance=false --build-arg SYSTEM_NLTK_DATA_PATH=$NLTK_DATA \
            --build-arg IMAGES_BUCKET_NAME=$IMAGES_BUCKET_NAME \
            --build-arg SYSTEM_MODEL_PATH=$SYSTEM_MODEL_PATH \
            -t image-classifier:$IMAGE_TAG -f docker/image-classifier/Dockerfile --no-cache .
          echo "image_tag=$IMAGE_TAG" >> $GITHUB_OUTPUT

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_ACCESS_SECRET_KEY}}
          aws-region: ${{inputs.AWS_REGION}}

      - name: Login to ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag and push image to Amazon ECR
        id: upload-image
        env:
          ECR_REGISTRY: ${{steps.login-ecr.outputs.registry}}
          IMAGE_TAG: ${{steps.build-docker-container.outputs.image_tag}}
          TAG_AS_LATEST: ${{inputs.tag-as-latest == true}}
        run: |
          docker tag image-classifier:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          if [ "$TAG_AS_LATEST" = "true" ]; then
            docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
            docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
          fi
          echo "image_path=${ECR_REGISTRY}/${ECR_REPOSITORY}:${IMAGE_TAG}" >> $GITHUB_OUTPUT
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT
