name: Build Gradle project

on:
  pull_request:
    branches:
      - 'develop'

env:
  AUTH_SERVER_URL: ${{vars.AUTH_SERVER_URL}}
  OIDC_CLIENT_ID: ${{vars.OIDC_CLIENT_ID}}
  OIDC_CLIENT_SECRET: ${{secrets.OIDC_CLIENT_SECRET}}
  OIDC_TEST_USER_USERNAME: ${{vars.OIDC_TEST_USER_USERNAME}}
  OIDC_TEST_USER_PASSWORD: ${{secrets.OIDC_TEST_USER_PASSWORD}}
  MONGODB_DATABASE_NAME: ${{vars.MONGODB_DATABASE_NAME}}
  TF_WORKSPACE: ${{vars.DEV_TF_WORKSPACE}}

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --warning-mode all
      - name: Upload image-processor build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-processor build reports
          path: image-processor/build/reports
      - name: Upload image-picker-api test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-picker-api test reports
          path: image-picker-api/build/reports
      - name: Upload image-cropper test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-cropper build reports
          path: image-cropper/build/reports

  build-native:
    needs: build-gradle-project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Build native API function
        run: ./gradlew image-picker-api:clean :image-picker-api:build -Dquarkus.package.type=native -x test -Dquarkus.native.resources.includes=application.properties -Dquarkus.native.container-build=true --info
      - name: Build native Image Processor
        run: ./gradlew :image-processor:clean :image-processor:build -Dquarkus.package.type=native -x test -Dquarkus.native.resources.includes=application.properties -Dquarkus.native.container-build=true --info
      - name: Build native Image Cropper
        run: ./gradlew image-cropper:clean :image-cropper:build -Dquarkus.package.type=native -x test -Dquarkus.native.resources.includes=application.properties -Dquarkus.native.container-build=true --info
      - name: Upload API function zip
        uses: actions/upload-artifact@v4
        with:
          name: api-function
          path: image-picker-api/build/function.zip
      - name: Upload Image Processor function zip
        uses: actions/upload-artifact@v4
        with:
          name: image-processor-function
          path: image-processor/build/function.zip
      - name: Upload Image Cropper function zip
        uses: actions/upload-artifact@v4
        with:
          name: image-cropper-function
          path: image-cropper/build/function.zip

  plan-terraform:
    runs-on: ubuntu-latest
    needs: build-native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download API zip
        uses: actions/download-artifact@v4
        with:
          name: api-function
      - name: Download Image Processor zip
        uses: actions/download-artifact@v4
        with:
          name: image-processor-function
      - name: Download Cropper Processor zip
        uses: actions/download-artifact@v4
        with:
          name: image-cropper-function
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
      - run: terraform init
        working-directory: terraform
      - run: terraform plan
        working-directory: terraform