name: Build Gradle project

on:
  pull_request:
    branches:
      - 'develop'

env:
  AUTH_SERVER_URL: ${{vars.AUTH_SERVER_URL}}
  OIDC_CLIENT_ID: ${{vars.OIDC_CLIENT_ID}}
  OIDC_CLIENT_SECRET: ${{secrets.OIDC_CLIENT_SECRET}}

jobs:
  build-gradle-project:
    runs-on: macos-14
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --warning-mode all
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Build reports
          path: build/reports