name: Build Gradle project

on:
  pull_request:
    branches:
      - 'develop'

env:
  AUTH_SERVER_URL: ${{vars.AUTH_SERVER_URL}}
  OIDC_CLIENT_ID: ${{vars.OIDC_CLIENT_ID}}
  OIDC_CLIENT_SECRET: ${{secrets.OIDC_CLIENT_SECRET}}

jobs:
  build-gradle-project:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project sources
        uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Run build with Gradle Wrapper
        run: ./gradlew build --warning-mode all
      - name: Upload image-processor build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-processor build reports
          path: image-processor/build/reports
      - name: Upload image-picker-api build artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: image-picker-api build reports
          path: image-picker-api/build/reports
