name: Pull request pipeline

on:
  pull_request:
    branches:
      - 'develop'

env:
  TF_WORKSPACE: ${{vars.DEV_TF_WORKSPACE}}

jobs:

  #  TODO: move to on-develop-merge when tested
  call-build-push-image-classifier:
    uses: ./.github/workflows/build-push-image-classifier.yml
    with:
      AWS_REGION: ${{vars.DEV_AWS_REGION}}
      IMAGES_BUCKET_NAME: ${{vars.DEV_IMAGES_BUCKET_NAME}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.DEV_AWS_ACCESS_KEY_ID}}
      AWS_ACCESS_SECRET_KEY: ${{secrets.DEV_AWS_ACCESS_SECRET_KEY}}

  print-outputs:
    needs: call-build-push-image-classifier
    runs-on: ubuntu-latest
    steps:
      - name: print the outputs
        run: |
          echo "The image tag is ${{needs.call-build-push-image-classifier.outputs.image_tag}}"
          echo "The image path is ${{needs.call-build-push-image-classifier.outputs.full_image_path}}"

  call-build-gradle-project:
    uses: ./.github/workflows/gradle-build.yml
    secrets: inherit

  call-build-native:
    needs: call-build-gradle-project
    uses: ./.github/workflows/build-native.yml
    secrets: inherit

  plan-terraform:
    runs-on: ubuntu-latest
    needs: call-build-native
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download API zip
        uses: actions/download-artifact@v4
        with:
          name: api-function
          path: image-picker-api/build
      - name: Download Image Processor zip
        uses: actions/download-artifact@v4
        with:
          name: image-processor-function
          path: image-processor/build
      - name: Download Cropper Processor zip
        uses: actions/download-artifact@v4
        with:
          name: image-cropper-function
          path: image-cropper/build
      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{secrets.TF_API_TOKEN}}
      - run: terraform init
        working-directory: terraform
      - run: terraform plan
        working-directory: terraform